controller_list:
  - name: fake_arm_controller
    joints:
      - rotation1_joint
      - shoulder1_joint
      - shoulder2_joint
      - rotation2_joint
      - shoulder3_joint
      - wrist_joint
  - name: fake_gripper_controller
    joints:
      - left_finger_joint
      - right_finger_joint