#ifndef RIC_SETTINGS_H
#define RIC_SETTINGS_H

#define INDICATOR_LED 13
#define BAUDRATE 115200
#define SEND_KA_INTERVAL 300 //ms
#define GET_KA_INTERVAL 1000 //ms
#define SEND_READINGS_INTERVAL 20 //ms
#define ULTRASONIC_PIN 14

#endif //RIC_SETTINGS_H
