global_frame: map
rolling_window: false
track_unknown_space: true

inflation_global:
    inflation_radius: 0.2
    cost_scaling_factor: 0.8

plugins:
#  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_global,               type: "costmap_2d::InflationLayer"}
