footprint: [[0.26, 0.26], [-0.26, 0.26], [-0.26, -0.26], [0.26, -0.26]]
footprint_padding: 0.00002

robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 1.0

origin_z: 0.0 
z_resolution: 0.02
z_voxels: 10


static:
    map_topic: /map
    subscribe_to_updates: true

inflation_radius: 1.75
cost_scaling_factor: 2.58


obstacles_layer:
    enabled: true
    obstacle_range: 4.5
    raytrace_range: 5.0
    observation_sources: laser
    laser: {sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

subscribe_to_updates: true
#always_send_full_costmap: true

#inflation:
#    cost_scaling_factor: 0.33
#    inflation_radius: 1.0 


