
plugins: 
- {name: explore_boundary,    type: "frontier_exploration::BoundedExploreLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
- {name: inflation_exploration,           type: "costmap_2d::InflationLayer"}

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: centroid # middle
  #set to false for gmapping, true if re-exploring a known area
  explore_clear_space: true
